#!/usr/bin/env bash
# Regenerates src/styles/fonts.css and src/styles/fonts/*.woff2 from Google
# Fonts. Both families are SIL Open Font License, which permits self-hosting.
#
# Self-hosted rather than linked because an @import of the Google stylesheet
# makes the font CSS a child request of our own CSS — the browser cannot ask
# for it until our stylesheet has parsed, and the font files are another hop
# after that. Serving them from our own origin also drops two DNS/TLS
# handshakes to third parties.
#
# Only the latin subset is kept; the UI is English. Add subsets here if that
# ever stops being true.
set -euo pipefail

cd "$(dirname "$0")/.."

FAMILIES='family=IBM+Plex+Mono:wght@400;500&family=Space+Grotesk:wght@400;500;600;700'
UA='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36'
SUBSET='latin'

rm -rf src/styles/fonts
mkdir -p src/styles/fonts
CSS=$(curl -fsSL -A "$UA" "https://fonts.googleapis.com/css2?${FAMILIES}&display=swap")

SUBSET="$SUBSET" python3 - "$CSS" <<'PY'
import os, pathlib, re, sys, urllib.request
from collections import defaultdict

css = sys.argv[1]
subset = os.environ["SUBSET"]
out_dir = pathlib.Path("src/styles/fonts")
blocks = re.findall(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", css, re.S)

# family -> url -> [weights].  Google serves a variable font as the *same* URL
# for every requested weight, so grouping by URL is what distinguishes a
# variable family from a set of static instances.
families: dict[str, dict[str, list[int]]] = defaultdict(lambda: defaultdict(list))
ranges: dict[str, str] = {}

for found, block in blocks:
    if found != subset:
        continue
    family = re.search(r"font-family: '([^']+)'", block).group(1)
    weight = int(re.search(r"font-weight: (\d+)", block).group(1))
    url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)
    families[family][url].append(weight)
    ranges[family] = re.search(r"unicode-range: ([^;]+);", block).group(1)

if not families:
    raise SystemExit(f"No @font-face blocks found for subset {subset!r}")

faces = []
for family, by_url in sorted(families.items()):
    slug = family.lower().replace(" ", "-")
    variable = len(by_url) == 1 and len(next(iter(by_url.values()))) > 1
    for url, weights in sorted(by_url.items(), key=lambda kv: min(kv[1])):
        weights.sort()
        name = f"{slug}.woff2" if variable else f"{slug}-{weights[0]}.woff2"
        urllib.request.urlretrieve(url, out_dir / name)
        size = (out_dir / name).stat().st_size
        decl = f"{weights[0]} {weights[-1]}" if variable else str(weights[0])
        faces.append((family, decl, name, ranges[family]))
        kind = f"variable {decl}" if variable else f"static {decl}"
        print(f"  {family:16} {kind:16} {name:26} {size / 1024:6.1f} kB")

header = (
    "/* Generated by scripts/fetch-fonts.sh — do not edit by hand.\n"
    f"   {subset} subset only; both families are SIL OFL.\n"
    "   A weight *range* means the file is a variable font: one download covers\n"
    "   every weight in that range. */\n"
)
body = "\n".join(
    f"""@font-face {{
  font-family: '{family}';
  font-style: normal;
  font-weight: {decl};
  font-display: swap;
  src: url('./fonts/{name}') format('woff2');
  unicode-range: {unicode_range};
}}
"""
    for family, decl, name, unicode_range in faces
)
pathlib.Path("src/styles/fonts.css").write_text(header + "\n" + body)
total = sum(p.stat().st_size for p in out_dir.glob("*.woff2"))
print(f"Wrote src/styles/fonts.css ({len(faces)} faces, {total / 1024:.1f} kB of fonts)")
PY
